#Write a program to input eight numbers from the user and display all the unique number(once).
s=set()
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
n=int(input("Enter the number here:-"))
s.add(n)
print(s)